# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
hostssl all             all             127.0.0.1/32            scram-sha-256
hostssl all             all             ::1/128                 scram-sha-256
hostssl replication     all             127.0.0.1/32            scram-sha-256
hostssl replication     all             ::1/128                 scram-sha-256
hostssl all             all             10.0.0.0/8              scram-sha-256
hostssl all             all             172.16.0.0/12           scram-sha-256
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::/0                    scram-sha-256
