#!/bin/bash
set -e

if [ -n "${PGBOUNCER_AUTH_USER:-}" ] && [ -n "${PGBOUNCER_AUTH_PASSWORD:-}" ]; then
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PGBOUNCER_AUTH_USER}') THEN
    CREATE ROLE ${PGBOUNCER_AUTH_USER} LOGIN PASSWORD '${PGBOUNCER_AUTH_PASSWORD}';
  ELSE
    ALTER ROLE ${PGBOUNCER_AUTH_USER} LOGIN PASSWORD '${PGBOUNCER_AUTH_PASSWORD}';
  END IF;
END
\$\$;
GRANT USAGE ON SCHEMA pgbouncer TO ${PGBOUNCER_AUTH_USER};
GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(TEXT) TO ${PGBOUNCER_AUTH_USER};
SQL
fi
